// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['handler']['App']['CheckUpdate']();
}

export function GetPoolInfoList(arg1) {
  return window['go']['handler']['App']['GetPoolInfoList'](arg1);
}

export function GetSettings() {
  return window['go']['handler']['App']['GetSettings']();
}

export function GetUserList() {
  return window['go']['handler']['App']['GetUserList']();
}

export function GetVersion() {
  return window['go']['handler']['App']['GetVersion']();
}

export function SetSetting(arg1, arg2) {
  return window['go']['handler']['App']['SetSetting'](arg1, arg2);
}

export function UpdateRecord() {
  return window['go']['handler']['App']['UpdateRecord']();
}

export function UpdateRecordFully() {
  return window['go']['handler']['App']['UpdateRecordFully']();
}

export function UpdateSelf() {
  return window['go']['handler']['App']['UpdateSelf']();
}
