// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestVersion() {
  return window['go']['handler']['App']['GetLatestVersion']();
}

export function GetPoolInfo(arg1, arg2) {
  return window['go']['handler']['App']['GetPoolInfo'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['handler']['App']['GetSetting'](arg1);
}

export function GetUserList() {
  return window['go']['handler']['App']['GetUserList']();
}

export function GetVersion() {
  return window['go']['handler']['App']['GetVersion']();
}

export function SetSetting(arg1, arg2) {
  return window['go']['handler']['App']['SetSetting'](arg1, arg2);
}

export function SyncRecordsCN() {
  return window['go']['handler']['App']['SyncRecordsCN']();
}

export function SyncRecordsOS() {
  return window['go']['handler']['App']['SyncRecordsOS']();
}

export function UpdateTo(arg1) {
  return window['go']['handler']['App']['UpdateTo'](arg1);
}
