// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';
import {model} from '../models';

export function CheckUpdate():Promise<boolean>;

export function GetPoolInfoList(arg1:number):Promise<Array<handler.PoolInfo>>;

export function GetSettings():Promise<Array<model.Setting>>;

export function GetUserList():Promise<Array<model.User>>;

export function GetVersion():Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateRecord():Promise<void>;

export function UpdateRecordFully():Promise<void>;

export function UpdateSelf():Promise<void>;
