// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';
import {model} from '../models';

export function GetLatestVersion():Promise<string>;

export function GetPoolInfo(arg1:number,arg2:number):Promise<handler.PoolInfo>;

export function GetSetting(arg1:string):Promise<string>;

export function GetUserList():Promise<Array<model.User>>;

export function GetVersion():Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateRecord():Promise<void>;

export function UpdateRecordFully():Promise<void>;

export function UpdateSelf():Promise<void>;
