// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: proto/LangPackageTableCnData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LangPackageTableCnData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*LangPackageTableCn `protobuf:"bytes,1,rep,name=Units,proto3" json:"Units,omitempty"`
}

func (x *LangPackageTableCnData) Reset() {
	*x = LangPackageTableCnData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LangPackageTableCnData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LangPackageTableCnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangPackageTableCnData) ProtoMessage() {}

func (x *LangPackageTableCnData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LangPackageTableCnData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangPackageTableCnData.ProtoReflect.Descriptor instead.
func (*LangPackageTableCnData) Descriptor() ([]byte, []int) {
	return file_proto_LangPackageTableCnData_proto_rawDescGZIP(), []int{0}
}

func (x *LangPackageTableCnData) GetUnits() []*LangPackageTableCn {
	if x != nil {
		return x.Units
	}
	return nil
}

type LangPackageTableCn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LangPackageTableCn) Reset() {
	*x = LangPackageTableCn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LangPackageTableCnData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LangPackageTableCn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangPackageTableCn) ProtoMessage() {}

func (x *LangPackageTableCn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LangPackageTableCnData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangPackageTableCn.ProtoReflect.Descriptor instead.
func (*LangPackageTableCn) Descriptor() ([]byte, []int) {
	return file_proto_LangPackageTableCnData_proto_rawDescGZIP(), []int{1}
}

func (x *LangPackageTableCn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LangPackageTableCn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_LangPackageTableCnData_proto protoreflect.FileDescriptor

var file_proto_LangPackageTableCnData_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4c, 0x61, 0x6e, 0x67, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x16, 0x4c, 0x61, 0x6e, 0x67, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29,
	0x0a, 0x05, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x4c, 0x61, 0x6e, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x6e, 0x52, 0x05, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x4c, 0x61, 0x6e,
	0x67, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_LangPackageTableCnData_proto_rawDescOnce sync.Once
	file_proto_LangPackageTableCnData_proto_rawDescData = file_proto_LangPackageTableCnData_proto_rawDesc
)

func file_proto_LangPackageTableCnData_proto_rawDescGZIP() []byte {
	file_proto_LangPackageTableCnData_proto_rawDescOnce.Do(func() {
		file_proto_LangPackageTableCnData_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_LangPackageTableCnData_proto_rawDescData)
	})
	return file_proto_LangPackageTableCnData_proto_rawDescData
}

var file_proto_LangPackageTableCnData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_LangPackageTableCnData_proto_goTypes = []any{
	(*LangPackageTableCnData)(nil), // 0: LangPackageTableCnData
	(*LangPackageTableCn)(nil),     // 1: LangPackageTableCn
}
var file_proto_LangPackageTableCnData_proto_depIdxs = []int32{
	1, // 0: LangPackageTableCnData.Units:type_name -> LangPackageTableCn
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_LangPackageTableCnData_proto_init() }
func file_proto_LangPackageTableCnData_proto_init() {
	if File_proto_LangPackageTableCnData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_LangPackageTableCnData_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LangPackageTableCnData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LangPackageTableCnData_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LangPackageTableCn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_LangPackageTableCnData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_LangPackageTableCnData_proto_goTypes,
		DependencyIndexes: file_proto_LangPackageTableCnData_proto_depIdxs,
		MessageInfos:      file_proto_LangPackageTableCnData_proto_msgTypes,
	}.Build()
	File_proto_LangPackageTableCnData_proto = out.File
	file_proto_LangPackageTableCnData_proto_rawDesc = nil
	file_proto_LangPackageTableCnData_proto_goTypes = nil
	file_proto_LangPackageTableCnData_proto_depIdxs = nil
}
